name: Build Pure K2P 4.4/5.1

# 工作流触发条件
on: 
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: build
    # 替换新版Ubuntu runner
    runs-on: ubuntu-22.04
    env:
      TNAME: K2P
      images_dir: /opt/images  # <--- 修复：去掉了末尾多余的斜杠
    steps:
      # checkout v2 升级 v4
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Prepare environment dependencies
        run: |
          sudo apt update
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext p7zip-full fakeroot

      - name: Run shellcheck static check
        run: sh ./trunk/tools/shellcheck.sh

      - name: Prepare cross toolchain
        run: |
          cd toolchain-mipsel
          sh dl_toolchain.sh

      - name: Start firmware build for all targets
        run: |
          cd trunk
          sed -i "0,/FIRMWARE_BUILDS_REV.*$/s//FIRMWARE_BUILDS_REV=$(date +%Y%m%d)/" versions.inc
          mkdir -p ${images_dir}
          fakeroot ./build_firmware_ci $TNAME
          if [ $? -eq 0 ]; then  # <--- 优化：= 改为 -eq
            cp -f images/*.trx ${images_dir}/$TNAME-4.4-$(date +%Y%m%d-%H%M).trx
          fi
          ./clear_tree_simple >/dev/null 2>&1
          echo "PackageName=$TNAME-4.4-$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV

      # upload-artifact v2 升级 v4
      - name: Upload build artifact
        if: ${{ github.event_name != 'release' }}  # <--- 优化：去掉了多余的 success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PackageName }}
          path: ${{ env.images_dir }}

      # 发布上传工具升级至v2最新版
      - name: Upload firmware to GitHub Release
        if: ${{ github.event_name == 'release' }}  # <--- 优化：去掉了多余的 success()
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.images_dir }}/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
